import type {
  AssetCategory,
  AssetId,
  PortfolioAsset,
} from "./portfolio-data";

export const PORTFOLIO_ASSETS_EN: PortfolioAsset[] = [
  {
    id: "music",
    number: "01",
    category: "Interests",
    objectLabel: "Gramophone",
    sectionTitle: "Sound Studio",
    trait: "I use sound to preserve emotions that resist explanation.",
    teaser: "Original music, demos, and sonic experiments",
    intro:
      "This studio holds melodies still taking shape, fragments in production, and each attempt to translate a feeling into sound. The content shown here is sample material designed to be replaced.",
    accent: "#e2a85f",
    status: "IN PROGRESS",
    lastUpdated: "JULY 2026",
    focus: {
      camera: [-0.8, 3.4, 2.4],
      target: [-5.0, 1.35, -4.7],
    },
    metrics: [
      { value: "12", label: "Sound sketches" },
      { value: "04", label: "Released works" },
      { value: "72 BPM", label: "Current pulse" },
    ],
    entries: [
      {
        eyebrow: "CURRENT SESSION",
        title: "After the Rain",
        body: "A nocturnal sketch shaped by wooden percussion, tape grain, and chords that never quite settle.",
        meta: "03:42 · Ambient / Neo-classical",
      },
      {
        eyebrow: "FIELD NOTE",
        title: "The City Breathing",
        body: "Subway doors, crossing signals, and birds at daybreak gathered into a playable archive of urban sound.",
        meta: "Field recording · In progress",
      },
      {
        eyebrow: "COLLABORATION",
        title: "An Open Chorus",
        body: "I am looking for a vocalist with a gift for narrative to help complete this still-untitled piece.",
        meta: "Remote · Open",
      },
    ],
    note: "Music is not a backdrop; it is another way I understand time.",
    specialty: "music",
    related: ["making", "photography", "ritual"],
  },
  {
    id: "fitness",
    number: "02",
    category: "Life",
    objectLabel: "Dumbbells & Yoga Mat",
    sectionTitle: "Body Practice",
    trait: "The body, too, is a lifelong work.",
    teaser: "Training rhythms, recovery principles, and progress notes",
    intro:
      "I am less interested in exhausting myself once than in keeping a relationship with my body through busy seasons, travel, and low points.",
    accent: "#8ec3aa",
    status: "CURRENT CYCLE · BUILD",
    lastUpdated: "WEEK 06",
    focus: {
      camera: [8.6, 3.8, 7.4],
      target: [5.2, 0.45, 1.6],
    },
    metrics: [
      { value: "4×", label: "Sessions per week" },
      { value: "7.5 h", label: "Average sleep" },
      { value: "RPE 7", label: "Current intensity" },
    ],
    entries: [
      {
        eyebrow: "MON / LOWER",
        title: "Strength & Stability",
        body: "Squat patterns, unilateral stability, and anti-rotation core work, followed by ten unhurried minutes of mobility.",
        meta: "55 min · Moderate",
      },
      {
        eyebrow: "WED / ENGINE",
        title: "Endurance & Mobility",
        body: "Zone 2 cardio paired with hip, ankle, and thoracic mobility. Fatigue is not proof that training worked.",
        meta: "45 min · Easy",
      },
      {
        eyebrow: "SAT / PLAY",
        title: "A Day Without Numbers",
        body: "A hike, a ball game, or any movement worth returning to—bringing the body back into ordinary life.",
        meta: "Outdoors · Untracked",
      },
    ],
    note: "Training that truly accumulates should leave something in reserve for tomorrow.",
    specialty: "fitness",
    related: ["growth", "ritual", "future"],
  },
  {
    id: "reading",
    number: "03",
    category: "Academic",
    objectLabel: "Bookshelf",
    sectionTitle: "Reading & Marginalia",
    trait: "Reading is not collecting answers; it is rehearsing another point of view.",
    teaser: "Thematic reading lists, excerpts, and personal annotations",
    intro:
      "The shelves are arranged by question rather than discipline: how to observe, how to create, and how to live with others. Excerpts are only entrances; what matters is what they change.",
    accent: "#d7c9a6",
    status: "ONGOING",
    lastUpdated: "38 NOTES",
    focus: {
      camera: [8.4, 3.7, -0.1],
      target: [5.45, 2.0, -5.35],
    },
    metrics: [
      { value: "26", label: "Books this year" },
      { value: "08", label: "Thematic paths" },
      { value: "143", label: "Personal notes" },
    ],
    entries: [
      {
        eyebrow: "PATH 01 · ATTENTION",
        title: "Learning to Look Again",
        body: "From visual culture to photography theory and everyday observation, tracing how attention is shaped by its surroundings.",
        meta: "6 books · 21 notes",
      },
      {
        eyebrow: "PATH 02 · SYSTEMS",
        title: "Small Actions in Complex Systems",
        body: "Returning systems thinking to lived experience: feedback, delay, boundaries, and the long gestures that can seem ineffective.",
        meta: "4 books · In progress",
      },
      {
        eyebrow: "RECENT MARGIN",
        title: "On the Unfinished",
        body: "The unfinished is not the opposite of completion. Sometimes it is how a question remains alive.",
        meta: "Personal note · 2 days ago",
      },
    ],
    note: "I do not want merely to finish a book; I want it to keep unfolding.",
    specialty: "reading",
    related: ["research", "growth", "about"],
  },
  {
    id: "research",
    number: "04",
    category: "Academic",
    objectLabel: "Research Desk",
    sectionTitle: "Research Desk",
    trait: "I tend to turn vague questions into things that can be tested.",
    teaser: "Research questions, methods, and chains of evidence",
    intro:
      "Every project begins with a question that is not yet clear enough, then moves through decomposition, testing, failure, and reframing. The process matters here as much as the conclusion.",
    accent: "#74b5b0",
    status: "2 QUESTIONS ACTIVE",
    lastUpdated: "Q3 2026",
    focus: {
      camera: [4.6, 3.35, 2.0],
      target: [0.5, 1.15, -3.65],
    },
    metrics: [
      { value: "02", label: "Active studies" },
      { value: "05", label: "Published papers" },
      { value: "11", label: "Method experiments" },
    ],
    entries: [
      {
        eyebrow: "QUESTION 01",
        title: "How Do Spatial Interfaces Shape Narrative Memory?",
        body: "Comparing index-based and spatial information architectures to see whether visitors more accurately remember relationships between people and content.",
        meta: "Mixed methods · Recruiting",
      },
      {
        eyebrow: "METHOD",
        title: "Turning Intuition into a Hypothesis",
        body: "First record what we expect to happen, then define evidence, counterexamples, and stopping rules to limit persuasion after the fact.",
        meta: "Research protocol v1.4",
      },
      {
        eyebrow: "OPEN MATERIAL",
        title: "Reproducible Records",
        body: "Research logs, data dictionaries, and key decisions remain versioned so the method can be understood, challenged, and reused.",
        meta: "Docs · Repository",
      },
    ],
    note: "Good research does not perform certainty; it makes uncertainty available for shared inquiry.",
    specialty: "research",
    related: ["reading", "making", "travel"],
  },
  {
    id: "making",
    number: "05",
    category: "Making",
    objectLabel: "Prototype Workbench",
    sectionTitle: "Making Lab",
    trait: "An idea begins to become honest only once it is made.",
    teaser: "Products, code, and interaction experiments",
    intro:
      "Everything here can run, fail, and be revised. Each case describes its aim, constraints, my contribution, and what comes next.",
    accent: "#e07a5f",
    status: "LAB OPEN",
    lastUpdated: "07 BUILDS",
    focus: {
      camera: [6.7, 3.55, 4.2],
      target: [2.75, 0.95, -1.35],
    },
    metrics: [
      { value: "07", label: "Released prototypes" },
      { value: "19", label: "Experimental branches" },
      { value: "3 d", label: "Average first build" },
    ],
    entries: [
      {
        eyebrow: "FEATURED BUILD",
        title: "Living Index",
        body: "Reimagining a personal site as an explorable space while retaining an accessible, searchable index of its contents.",
        meta: "Three.js · React · TypeScript",
      },
      {
        eyebrow: "MICRO TOOL",
        title: "Thinking Card Machine",
        body: "A small set of constraints helps recurring questions emerge from scattered notes, without building yet another note warehouse.",
        meta: "Prototype · Local-first",
      },
      {
        eyebrow: "FAILED WELL",
        title: "An Exercise in Overdesign",
        body: "After removing 60% of the interactions, users could finally say what the page was helping them do.",
        meta: "Retrospective · 6 min read",
      },
    ],
    note: "I like prototypes because they quickly reveal what language has left unclear.",
    specialty: "gallery",
    related: ["research", "music", "future"],
  },
  {
    id: "photography",
    number: "06",
    category: "Interests",
    objectLabel: "Camera",
    sectionTitle: "Through the Viewfinder",
    trait: "What I photograph is a way of seeing the world.",
    teaser: "Photographic series and visual journals",
    intro:
      "This is not a list of destinations, but a sustained practice in light, distance, and how people remain within a scene. Each series includes a short field note.",
    accent: "#c9b5d4",
    status: "3 SERIES",
    lastUpdated: "ROLL 27",
    focus: {
      camera: [4.8, 3.3, 8.1],
      target: [0.0, 0.95, 2.45],
    },
    metrics: [
      { value: "03", label: "Long-term series" },
      { value: "27", label: "Rolls archived" },
      { value: "50 mm", label: "Usual perspective" },
    ],
    entries: [
      {
        eyebrow: "SERIES 01",
        title: "The Lights Are Still On",
        body: "Windows where someone is still working, waiting, tidying, or returning home in the city at night.",
        meta: "24 frames · Shanghai",
      },
      {
        eyebrow: "SERIES 02",
        title: "Temporary Tables",
        body: "How, amid moving, travel, and brief stays, a few objects can rebuild a corner that feels like one's own.",
        meta: "18 frames · Ongoing",
      },
      {
        eyebrow: "CONTACT SHEET",
        title: "The Photographs I Did Not Choose",
        body: "Failed compositions and missed moments remain in the archive; they often reveal more about how I was looking than the final edit.",
        meta: "Process archive",
      },
    ],
    note: "The camera slows me down, and makes me admit that I am always choosing.",
    specialty: "gallery",
    related: ["travel", "music", "ritual"],
  },
  {
    id: "ritual",
    number: "07",
    category: "Life",
    objectLabel: "Tea Table",
    sectionTitle: "Everyday Tastes",
    trait: "Giving an ordinary day a measure of my own.",
    teaser: "Food, city fragments, and the stories held by objects",
    intro:
      "There are no efficiency metrics here. This section records the temperature of tea, a breakfast often repeated, and the ways worth slowing down to welcome someone.",
    accent: "#b7c58b",
    status: "SLOW ARCHIVE",
    lastUpdated: "12 MOMENTS",
    focus: {
      camera: [1.1, 3.15, 4.8],
      target: [-3.55, 0.9, -0.55],
    },
    metrics: [
      { value: "06:40", label: "First glass of water" },
      { value: "82°C", label: "Usual water temperature" },
      { value: "Sunday", label: "Left unscheduled" },
    ],
    entries: [
      {
        eyebrow: "MORNING",
        title: "Ten Minutes Without Input",
        body: "No messages and nothing playing—only an open window, letting the day arrive before it is arranged.",
        meta: "Daily ritual",
      },
      {
        eyebrow: "OBJECT STORY",
        title: "A Mended Cup",
        body: "It no longer matches the set and is no longer perfect, but each use reminds me that remaining is a value of its own.",
        meta: "6 years together",
      },
      {
        eyebrow: "CITY NOTE",
        title: "A Route for Rainy Days",
        body: "A slower way home that passes a secondhand bookshop and a row of plane trees.",
        meta: "31°14′N · 121°28′E",
      },
    ],
    note: "The texture of a life is mostly made by repetitions no one sees.",
    specialty: "timeline",
    related: ["growth", "photography", "fitness"],
  },
  {
    id: "growth",
    number: "08",
    category: "Growth",
    objectLabel: "Plant",
    sectionTitle: "Growth Notes",
    trait: "I place more trust in growth that is slow and repeatable.",
    teaser: "Habit systems, monthly reflections, and a learning queue",
    intro:
      "The aim is not to fill every day, but to find the smallest actions that survive changes in energy. I share methods and reflections here, while keeping overly private data private.",
    accent: "#70a37f",
    status: "DAY 184",
    lastUpdated: "JULY REVIEW",
    focus: {
      camera: [-1.25, 3.9, 4.7],
      target: [-6.25, 1.35, -1.6],
    },
    metrics: [
      { value: "03", label: "Current habits" },
      { value: "01", label: "Intentionally released" },
      { value: "86%", label: "Reviews completed" },
    ],
    entries: [
      {
        eyebrow: "KEEP",
        title: "Leave One Searchable Judgment Each Day",
        body: "Not a long record—only how I decided in the moment, and what future evidence would change my mind.",
        meta: "Knowledge habit",
      },
      {
        eyebrow: "LEARN",
        title: "Relearning Probability & Uncertainty",
        body: "Returning formulas to real choices: forecasts, base rates, calibration, and the practice of admitting what I do not know.",
        meta: "8-week path",
      },
      {
        eyebrow: "LET GO",
        title: "Stop Tracking Everything",
        body: "When recording begins to replace living, remove one metric and return attention to the change that actually matters.",
        meta: "July decision",
      },
    ],
    note: "Stability is not sameness every day; it is knowing how to return.",
    specialty: "timeline",
    related: ["fitness", "reading", "future"],
  },
  {
    id: "about",
    number: "09",
    category: "Growth",
    objectLabel: "Mirror",
    sectionTitle: "About Me",
    trait: "More enduring than a title, and more specific than a résumé.",
    teaser: "Identity, working principles, and what I am still learning",
    intro:
      "Hello, I am “Your Name.” I work across research, design, and technology, and I am still learning how to make complex things clear, humane, and useful.",
    accent: "#b5d5d8",
    status: "AVAILABLE",
    lastUpdated: "GMT+8",
    focus: {
      camera: [-1.5, 4.15, 6.8],
      target: [-7.75, 2.3, 1.35],
    },
    metrics: [
      { value: "CN / EN", label: "Working languages" },
      { value: "GMT+8", label: "Time zone" },
      { value: "∞", label: "Still learning" },
    ],
    entries: [
      {
        eyebrow: "I DO",
        title: "Make the Vague Discussable",
        body: "I frame questions, build prototypes, test judgments, and explain the process to people from different backgrounds.",
        meta: "Research · Design · Code",
      },
      {
        eyebrow: "I VALUE",
        title: "Clarity, Honesty, and Room to Move",
        body: "I do not pretend complexity is simple, nor use complexity as an excuse for inaction.",
        meta: "Working principles",
      },
      {
        eyebrow: "I AM LEARNING",
        title: "How to Finish Things Together",
        body: "To offer a judgment while leaving room to listen, so collaboration is not only faster but the result genuinely belongs to those involved.",
        meta: "Ongoing practice",
      },
    ],
    note: "I hope my work reveals what I can do, and my days reveal what I choose.",
    specialty: "default",
    related: ["contact", "research", "growth"],
  },
  {
    id: "travel",
    number: "10",
    category: "Relations",
    objectLabel: "Postcard Wall",
    sectionTitle: "Where I Come From",
    trait: "I come from many places, and have been illuminated by many people.",
    teaser: "Cities, journeys, and formative passages",
    intro:
      "Maps keep coordinates; postcards keep relationships. This wall gathers the places, companions, and remembered words that changed how I see.",
    accent: "#efb6a0",
    status: "MEMORY MAP",
    lastUpdated: "09 PLACES",
    focus: {
      camera: [6.8, 4.35, -0.55],
      target: [2.85, 3.25, -5.72],
    },
    metrics: [
      { value: "09", label: "Meaningful coordinates" },
      { value: "04", label: "Enduring relationships" },
      { value: "2018—", label: "Years documented" },
    ],
    entries: [
      {
        eyebrow: "31°14′N",
        title: "Keeping a Human Scale in a Vast City",
        body: "It begins with a familiar street, someone who remembers your taste, and a tree you pass again and again.",
        meta: "Shanghai · Home",
      },
      {
        eyebrow: "35°41′N",
        title: "Rethinking Order and Empty Space",
        body: "Not reducing everything to a minimum, but giving each remaining thing enough room to unfold.",
        meta: "Tokyo · Field note",
      },
      {
        eyebrow: "THANK YOU",
        title: "The People Outside the Credits",
        body: "They offered rooms, dinners, candid disagreement, and the patience to wait when the outcome was uncertain.",
        meta: "Private acknowledgements",
      },
    ],
    note: "Belonging is not finding a place that never changes, but knowing which relationships are worth carrying.",
    specialty: "timeline",
    related: ["photography", "contact", "about"],
  },
  {
    id: "contact",
    number: "11",
    category: "Relations",
    objectLabel: "Telephone",
    sectionTitle: "Leave a Note",
    trait: "If you are making something with care, perhaps we should talk.",
    teaser: "Ways to collaborate, contact details, and conversational boundaries",
    intro:
      "There is no need to sound formal. Tell me what you are making, where you are stuck, and why a conversation together came to mind. Replace the sample contact details with your own.",
    accent: "#e8c57a",
    status: "OPEN TO TALK",
    lastUpdated: "REPLY IN 2–3 DAYS",
    focus: {
      camera: [4.35, 2.8, 1.55],
      target: [1.7, 1.15, -3.55],
    },
    metrics: [
      { value: "2–3 d", label: "Typical reply" },
      { value: "GMT+8", label: "Time zone" },
      { value: "Remote", label: "Collaboration mode" },
    ],
    entries: [
      {
        eyebrow: "WELCOME",
        title: "Research & Interactive Narrative",
        body: "I especially welcome long-term questions around knowledge tools, spatial interfaces, cultural content, and public value.",
        meta: "Project collaboration",
      },
      {
        eyebrow: "ALSO",
        title: "Share an Idea Still Taking Shape",
        body: "It need not be complete. A prepared conversation is often more valuable than a polished proposal.",
        meta: "Conversation · 30 min",
      },
      {
        eyebrow: "CONTACT",
        title: "hello@your-domain.com",
        body: "Before publishing, replace the email address, social links, and personal domain. Do not place a private phone number on a public page.",
        meta: "Email · Preferred",
      },
    ],
    note: "Clear boundaries make the conversations that matter easier to begin.",
    specialty: "default",
    related: ["about", "making", "travel"],
  },
  {
    id: "future",
    number: "12",
    category: "Growth",
    objectLabel: "Unopened Door",
    sectionTitle: "The Next Room",
    trait: "Some rooms are still being built.",
    teaser: "A public roadmap for the next 6–12 months",
    intro:
      "This is more than “coming soon.” It is a revisable account of direction: questions I plan to pursue, work I hope to finish, and things I would gladly begin with others.",
    accent: "#9c90c8",
    status: "ROADMAP",
    lastUpdated: "2026 → 2027",
    focus: {
      camera: [1.8, 3.75, 0.35],
      target: [-2.35, 1.75, -5.72],
    },
    metrics: [
      { value: "03", label: "Next steps" },
      { value: "12 mo", label: "Planning horizon" },
      { value: "OPEN", label: "Build together" },
    ],
    entries: [
      {
        eyebrow: "NEXT 01",
        title: "Turn This Room into an Open Method",
        body: "Document methods for spatial narrative, accessible navigation, and content modeling so more people can build digital rooms of their own.",
        meta: "Open-source · Q4",
      },
      {
        eyebrow: "NEXT 02",
        title: "Complete a Piece of Music",
        body: "Move from accumulating sketches to finishing, releasing, and building a full cycle of feedback with real listeners.",
        meta: "Music · Winter",
      },
      {
        eyebrow: "INVITATION",
        title: "Find a Question Worth Studying Together",
        body: "One that crosses disciplines, remains close to lived experience, and allows us to stay patient before an answer appears.",
        meta: "Collaboration · Open",
      },
    ],
    note: "Direction is not a promise never to change; it is an account of why I am moving this way now.",
    specialty: "research",
    related: ["making", "growth", "contact"],
  },
];

export const ASSET_BY_ID_EN = Object.fromEntries(
  PORTFOLIO_ASSETS_EN.map((asset) => [asset.id, asset]),
) as Record<AssetId, PortfolioAsset>;

export const CATEGORY_ORDER_EN = [
  "Life",
  "Interests",
  "Academic",
  "Making",
  "Relations",
  "Growth",
] as const satisfies readonly AssetCategory[];
